Importer les modules necessaires

In [1]:
import pandas as pd
import tensorflow as tf
import keras as k
import numpy as np
import matplotlib.pyplot as plt
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import to_categorical
from sklearn.metrics import confusion_matrix

Using TensorFlow backend.


Preparer le jeu de donner, diviser en base d'apprentissage et de test

In [2]:
dataset = pd.read_csv('optic.csv', delimiter = ";")
dataset = pd.DataFrame(np.random.randn(3822,65))
msk = np.random.rand(len(dataset)) < 0.8
optic_train = dataset[msk]
optic_test = dataset[~msk]
len(optic_train)
len(optic_test)
optic_train.shape

(3084, 65)

Apprentissage

In [3]:
x = optic_train.iloc[:,1:65]
y = optic_train.iloc[:,-1]
x.shape

(3084, 64)

Test

In [4]:
x_test = optic_test.iloc[:,1:65]
y_test = optic_test.iloc[:,-1]
x_test.shape

(738, 64)

Encodage des labels

In [5]:
encode_y = to_categorical(y)
encode_ytest = to_categorical(y_test)
encode_y.shape

(3084, 4)

Creation du modele

In [6]:
model = Sequential()
model.add(Dense(units = 32, kernel_initializer = 'uniform' , activation = 'relu' , input_dim = 64))
model.add(Dense(units = 28, kernel_initializer = 'uniform' , activation = 'relu'))
model.add(Dense(units = 16, kernel_initializer = 'uniform' , activation = 'relu'))
model.add(Dense(units = 8, kernel_initializer = 'uniform' , activation = 'relu'))
model.add(Dense(units = 4, kernel_initializer = 'uniform' , activation = 'softmax'))

Impression du modele

In [7]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 32)                2080      
_________________________________________________________________
dense_2 (Dense)              (None, 28)                924       
_________________________________________________________________
dense_3 (Dense)              (None, 16)                464       
_________________________________________________________________
dense_4 (Dense)              (None, 8)                 136       
_________________________________________________________________
dense_5 (Dense)              (None, 4)                 36        
Total params: 3,640
Trainable params: 3,640
Non-trainable params: 0
_________________________________________________________________


Ajout de la fonction de perte, l'optimiseur et la precision pour le modele

In [8]:
model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

Execution de l'apprentissage du modele

In [9]:
model.fit(x, encode_y, batch_size = 28, epochs = 50)

Epoch 1/50
3084/3084 [==============================] - 1s 226us/step - loss: 0.5074 - acc: 0.7710
Epoch 2/50
3084/3084 [==============================] - 0s 64us/step - loss: 0.4102 - acc: 0.8339
Epoch 3/50
3084/3084 [==============================] - 0s 63us/step - loss: 0.4024 - acc: 0.8334
Epoch 4/50
3084/3084 [==============================] - 0s 63us/step - loss: 0.3992 - acc: 0.8345
Epoch 5/50
3084/3084 [==============================] - 0s 64us/step - loss: 0.3958 - acc: 0.8352
Epoch 6/50
3084/3084 [==============================] - 0s 65us/step - loss: 0.3937 - acc: 0.8359
Epoch 7/50
3084/3084 [==============================] - 0s 65us/step - loss: 0.3903 - acc: 0.8367
Epoch 8/50
3084/3084 [==============================] - 0s 63us/step - loss: 0.3877 - acc: 0.8373
Epoch 9/50
3084/3084 [==============================] - 0s 64us/step - loss: 0.3833 - acc: 0.8382
Epoch 10/50
3084/3084 [==============================] - 0s 63us/step - loss: 0.3794 - acc: 0.8411
Epoch 11/50
3084/3

Prediction a partir des donnees de test

In [10]:
y_predict = model.predict(x_test)
y_predict = (y_predict >= 0.18)
print(y_predict)

[[ True False False False]
 [ True  True False  True]
 [ True False False False]
 ..., 
 [ True False False False]
 [ True  True False  True]
 [False  True False  True]]


Matrice de confusion

In [11]:
con_m = confusion_matrix(encode_ytest.argmax(axis=1), y_predict.argmax(axis=1))
print(con_m)

[[349 142   0   0]
 [ 82  33   0   0]
 [ 27  16   0   0]
 [ 64  25   0   0]]
